contact_links:
  - name: Ask a question
    url: https://github.com/mjkid221/fff-cctp-bridge/discussions
    about: Ask questions and discuss with other community members
  - name: Feature request
    url: https://github.com/mjkid221/fff-cctp-bridge/discussions/new?category=ideas
    about: Feature requests should be opened as discussions
